# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'AFNetworking', '1.3.4'
pod 'DACircularProgress'
pod 'pop'

end
